"""date column added to games

Revision ID: 2cc4f3daac97
Revises: 49fbd00aaff8
Create Date: 2019-08-06 19:28:39.852113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc4f3daac97'
down_revision = '49fbd00aaff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'date')
    # ### end Alembic commands ###
